# fly.toml app configuration file generated for rating-b on 2023-05-28T17:49:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rating-b"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
  release_command = "/app/.venv/bin/python manage.py migrate"

[env]
  PORT = "8000"
  PRIMARY_REGION = "waw"

[processes]
  cron = "supercronic /app/crontab"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
